title: Ars Computationis
description: >
  Ars Computationis (Art of Computation) is a blog maintained by André
  Ramaciotti da Silva.  It contains articles on programming, Computer Science,
  and (maybe) some personal stuff.
baseurl: ""
url: "https://ramaciotti.github.io"
github_username: ramaciotti

# Build settings
markdown: kramdown

exclude: ["Gemfile", "Gemfile.lock", "vendor"]
