title: André Ramaciotti
description: >
  Full-Stack Developer since 2010 with experience with C#, Java, and Ruby.
  B.Sc. Computer Science at FURB and B.Sc. Accounting student at FUMEC.
baseurl: ""
url: "https://www.ramaciotti.com"
github_username: ramaciotti

# Build settings
markdown: kramdown

exclude: ["Gemfile", "Gemfile.lock", "vendor"]
